[package]
name = "raclette"
version = "0.1.0"
authors = ["Roman Kashitsyn <roman@dfinity.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
term = "0.6.0"

[[test]]
name = "main"
harness = false
